[package]
name = "bc-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
json = "0.12.4"
bc-protocal-lib = { path = "../bc-protocal-lib" }
crossbeam-channel = "0.5.6"
