[package]
name = "bc-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
bc-protocal-lib = { path = "../bc-protocal-lib" }
json = "0.12.4"
crossbeam-channel = "0.5.6"
